apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: default
spec:
  rules:
    - host: kubernetes.academichain.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-ui
                port:
                  number: 80
    - host: kibana.academichain.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-service  # Replace with the actual Kibana service name
                port:
                  number: 5601
