apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: default
spec:
  rules:
    - host: academi.semicorp.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ .Chart.Name }}-ui
                port:
                  number: 80