apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: default  # Adjust the namespace as needed
spec:
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: beats
  selector:
    app: logstash
  type: ClusterIP  # Use LoadBalancer if external access is required
