apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ .Chart.Name }}-ui
spec:
  replicas: {{ .Values.core_service.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-ui
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui_service.repository }}:{{ .Values.ui_service.tag }}"
          imagePullPolicy: {{ .Values.ui_service.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ui_service.service.port }}
          env:
            - name: ACADEMICHAIN_ENV
              value: {{ .Values.ui_service.ACADEMICHAIN_ENV}}
            - name: POSTGRESHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESHOST
            - name: POSTGRESPORT
              value: {{ .Values.env.POSTGRESPORT | quote }}
            - name: POSTGRESUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESUSER
            - name: POSTGRESPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESPASSWORD
            - name: POSTGRESDBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESDB
            - name: CORE_SERVICE_URI
              value: "http://{{ .Chart.Name }}-core:{{ .Values.core_service.service.port }}/api/v1"
            - name: USER_SERVICE_URI
              value: "http://{{ .Chart.Name }}-users:{{ .Values.users_service.service.port }}/api/v1"
            - name: ITEM_SERVICE_URI
              value: "http://{{ .Chart.Name }}-items:{{ .Values.items_service.service.port }}/api/v1"
            - name: NLP_SERVICE_URI
              value: http://semicorp.org:9050
            - name: NLP_SERVICE_TOKEN
              value: 2hE#4Wr7EPGappqYeSu&iFZca9nW!tdjfqHzxv#vP^mB
            - name: REDIS_URL
              value: "tcp://student:TxoQ5TgjXx9RnrJGeBPWC2XzbGjASsJ@semicorp.org:6379"
            - name: ENCRYPTION_KEY
              value: vjLFfQoanpJtwu8M2VIAJdJessqw2UKAANdU+Z0t1nI=
            - name: KEYCLOAK_AUTH_URL
              value: "http://sever3d.synology.me:7080/auth/realms/academichain/protocol/openid-connect/token"
          resources:
            requests:
              memory: '128Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '1000m'
      initContainers:
        - name: database-migration
          image: sever3d/academichain-ui-database:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRESHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESHOST
            - name: POSTGRESPORT
              value: {{ .Values.env.POSTGRESPORT | quote }}
            - name: POSTGRESUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESUSER
            - name: POSTGRESPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESPASSWORD
            - name: POSTGRESDB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESDB
          args:
            - "--url=jdbc:postgresql://$(POSTGRESHOST):$(POSTGRESPORT)/$(POSTGRESDB)"
            - "--username=$(POSTGRESUSER)"
            - "--password=$(POSTGRESPASSWORD)"
            - "--changeLogFile=changelog/db.changelog-main.yml"
            - "--liquibaseSchemaName=uilogs"
            - "update"

