
core_service:
  repository: sever3d/academichain-core-service
  pullPolicy: Always
  tag: "latest"
  service:
    type: ClusterIP
    port: 9090
  replicas: 1

users_service:
  repository: sever3d/academichain-user-service
  pullPolicy: Always
  tag: "latest"
  service:
    type: ClusterIP
    port: 9091
  replicas: 1


items_service:
  repository: sever3d/academichain-item-service
  pullPolicy: Always
  tag: "latest"
  service:
    type: ClusterIP
    port: 9092
  replicas: 2

ui_service:
  repository: sever3d/academichain-ui
  pullPolicy: Always
  tag: "latest"
  service:
    type: ClusterIP
    port: 80
  replicas: 2
  ACADEMICHAIN_ENV: dev

env:
  POSTGRESPORT: 5432

resources: {}