
core_service:
  repository: sever3d/academichain-core-service
  pullPolicy: Always
  tag: "latest"
  service:
    type: ClusterIP
    port: 9090
  replicas: 1

env:
  POSTGRESPORT: 5432

resources: {}